### ISSUE TITLE
Connection timeout is not handled

### ISSUE THREAD

**Issue by BasKiers** [timonreinhard/wemo-client#44]
Hi,

Im using your library but after a certain amount of time (1-2 days or something) I get an ETIMEDOUT exception. Is this something you can handle in your library and if not where should I handle this exception and establish a new connection?

Regards,
Bas

 
Stack trace:

Error: connect ETIMEDOUT 192.168.1.61:49153
at Object.exports._errnoException (util.js:907:11)
at exports._exceptionWithHostPort (util.js:930:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

**Comment by timonreinhard** [comment]
Hi Bas,

thanks for reporting this issue. This should be definitely handled by the client indeed. Can you provide the full stack trace and log output (preferably when running with `DEBUG=wemo-client`)?

**Comment by timonreinhard** [comment]
I just verified your issue. The client emits an error event in the given case, which is correct. You need however to bind to this event as node.js would otherwise terminate with `Unhandled 'error' event`. This is by design as you'll want to handle those errors (e.g. device went offline) in your app and wait for the failing device to reappear via the discovery.

See [examples/maker.js#19](https://github.com/timonreinhard/wemo-client/blob/37a345dd90a4e998a6a5cc7d3db4a8249bd8deab/examples/maker.js#L19) on how to listen for client errors. When a listener is added, it won't crash anymore.
