### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by timonreinhard** [timonreinhard/wemo-client#69]
My last commit is from 3 years ago and that won't change anytime soon, as I stopped tinkering with Wemo devices a while ago. While the Wemo APIs are apparently quite stable, this repository has grown a lot of outdated dependencies and I just don't have the time to fix this. That is, why I'm considering putting this repo to read-only or transfer it to someone else who's willing to maintain it in the future.

Are there any forks out there that you'd recommend to use over this stale repository?

**Comment by bwp91** [comment]
Hi @timonreinhard 
My first instincts are not to take this repo on but is there a way i can contact you directly?
My email is bwp91@icloud.com if you’re happy to email?

**Comment by jimmywarting** [comment]
I'd be willing to take up maintainership for this project. My company is looking to use this project, I'm a core team member of the popular node-fetch package since the very first besinning and takes care of a number of other popular open source project.
I know a thing or two about open source and making sure it's harmful and well documented and safe

That being said, I have had a fascination of getting things modernized. My motivations are not to prioritize the needs of my company over the needs of the community. Looking through the issues, I think that I could help with answering the questions people have or looking into (and potentially fixing) the problems that are presented.

If it's alright with you then I would like to get full maintainership of npm package and that the github is transfered to my account along with all the issues/PR that comes with it

Just let me know 👍

**Comment by timonreinhard** [comment]
Transferring wemo-client to @jimmywarting
